[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyC4K6sj4MR1ggtd_zPRBC_vcHulPAKqq-k"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "dream-ai-dashboard.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "dream-ai-dashboard"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "dream-ai-dashboard.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "123456789"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:123456789:web:abcdef123456"
  NEXT_PUBLIC_GEMINI_API_KEY = "AIzaSyC4K6sj4MR1ggtd_zPRBC_vcHulPAKqq-k"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"